---
name: Build and push docker image for edirect in ubuntu user mode

on:
  push:
    branches:
      - main
    paths:
        - 'ubuntu-user/**'
  workflow_dispatch:

jobs:
  docker-build-edirect-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ycya88
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd ubuntu-user
          UBUNTU_VERSION=$(grep -oP '^ARG UBUNTU_VERSION=\K.*' Dockerfile)
          echo "UBUNTU_VERSION=${UBUNTU_VERSION}" >> $GITHUB_ENV
          echo "UBUNTU_VERSION=${UBUNTU_VERSION}"
          EDIRECT_VERSION=$(grep -oP '^ARG EDIRECT_VERSION=\K.*' Dockerfile)
          echo "EDIRECT_VERSION=${EDIRECT_VERSION}" >> $GITHUB_ENV
          echo "EDIRECT_VERSION=${EDIRECT_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ubuntu-user
          file: ubuntu-user/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ycya88/ncbi_edirect:${{ env.EDIRECT_VERSION }}-ubuntu${{ env.UBUNTU_VERSION }}
            ycya88/ncbi_edirect:${{ env.EDIRECT_VERSION }}
            ycya88/ncbi_edirect:ubuntu${{ env.UBUNTU_VERSION }}
            ycya88/ncbi_edirect:ubuntu
            ycya88/ncbi_edirect:latest
